addons:
  apt:
    packages:
    - libxml-xpath-perl
    - python3-pip
sudo: required
language: java
jdk: openjdk8
deploy:
- provider: script
  script:
  - "pip3 install -r requirements.txt && python3 ./src/main/scripts/cd/travis_tests.py"
  on:
    branch: feature/internal_tests
- provider: script
  script:
  - "pip3 install -r requirements.txt && python3 ./src/main/scripts/cd/travis_tests.py"
  on:
    branch: develop
